### ISSUE TITLE
AbortController issue

### ISSUE THREAD

**Issue by akarale** [Airtable/airtable.js#204]
TypeError: AbortController is not a constructor

Anyone else getting this error? How did you resolve it?

**Comment by jugglinmike** [comment]
Not me! But I might be able to help with more information.

- Which version of airtable.js are you using?
- What is the complete error stack?
- In what environment are you observing the error? If Node.js, the version of Node.js may help. If a web browser, the name and version of the browser may help.
- Can you provide a minimal test case?

**Comment by Aias** [comment]
I've also been getting this error after trying to upgrade to airtable 0.9.0 Glad I'm not the only one.

For a long time now I've been using airtable.js in my [Netlify lambda functions](https://docs.netlify.com/functions/build-with-javascript/#format), but upgrading to 0.9.0 has broken it without a resolution that I can find. If I go back to 0.8.1 it works fine, so there seems to be something going on with the recent move to `node-fetch` over `request`.

The Node version is 10.21.0.

Here's the full stack, though I'm not sure it's particularly helpful:

```
Lambda server is listening on 9000
Request from ::1: GET /.netlify/functions/airtableGet?base=commonplace&table=extracts
Response with status 500 in 57 ms.
Error during invocation:  TypeError: AbortController is not a constructor
    at runAction (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:9585:22)
    at Base.runAction (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:4780:5)
    at inner (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:8111:27)
    at Query.eachPage (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:8134:5)
    at Query.eachPage (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:1665:16)
    at Object.exports.handler (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:10666:6)
    at /Users/tricknombley/Code/netlify-api/node_modules/netlify-lambda/lib/serve.js:146:27
    at Layer.handle [as handle_request] (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/route.js:131:14)
```

A minimal test case would probably involve setting up a super basic Netlify lambda environment with the following single function:

```js
var Airtable = require('airtable');
var base = new Airtable({ apiKey: '<my key>' }).base('<my base>');

exports.handler = async function (event, context) {
    base('<table name>')
        .select({
            // Selecting the first 3 records in Grid view:
            maxRecords: 3,
            view: 'Grid view'
        })
        .eachPage(
            function page(records, fetchNextPage) {
                // This function (`page`) will get called for each page of records.

                records.forEach(function (record) {
                    console.log('Retrieved', record.get('title'));
                });

                // To fetch the next page of records, call `fetchNextPage`.
                // If there are more records, `page` will get called again.
                // If there are no more records, `done` will get called.
                fetchNextPage();
            },
            function done(err) {
                if (err) {
                    console.error(err);
                    return;
                }
            }
        );
};

```

**Comment by reelmatt** [comment]
Given the error name, it looks like this points to line 46 in `lib/base.js`:
```javascript
var controller = new AbortController();
```

While I haven't gotten a working solution yet, playing around with it a bit is seems like the issue is related to the switch from `request` to `node-fetch` as @Aias mentioned and how the library deals with Polyfills ([the `AbortController` interface is experimental, per MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)).

I also opened #205 which could be pointing to the same/similar issue, but could also be Jest-specific instead of a problem related to Airtable.js.

**Comment by jugglinmike** [comment]
@Aias Version 0.9.0 works for me using [Netlify's CLI for local testing](https://github.com/netlify/cli) and Node.js version 10.21.0. There may be subtle differences in the production environment, but there are other causes that could explain this. For starters: is `global.window` defined in your lambda function?

**Comment by jugglinmike** [comment]
@reelmatt Jest users should be able to upgrade to version 0.9.0 by installing [the `whatwg-fetch` module](https://www.npmjs.com/package/whatwg-fetch) and including that in their test environment via [the `--setupFiles` option](https://jestjs.io/docs/en/configuration#setupfiles-array).

Here's a quick demo:

    $ ./node_modules/.bin/jest
     FAIL  ./index.test.js
      ● Test suite failed to run

        ReferenceError: Request is not defined

        > 1 | const Airtable = require('airtable');
            |                  ^
          2 |
          3 | test('my test', async () => {
          4 |       Airtable.configure({

          at Object.<anonymous> (node_modules/airtable/lib/abort-controller.js:5:25)
          at Object.<anonymous> (node_modules/airtable/lib/base.js:8:23)
          at Object.<anonymous> (node_modules/airtable/lib/airtable.js:3:12)
          at Object.<anonymous> (index.test.js:1:18)

    Test Suites: 1 failed, 1 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        0.849 s, estimated 1 s
    Ran all test suites.

    $ npm install --save-dev whatwg-fetch
    $ ./node_modules/.bin/jest --setupFiles whatwg-fetch
     PASS  ./index.test.js
      ✓ my test (363 ms)

    Test Suites: 1 passed, 1 total
    Tests:       1 passed, 1 total
    Snapshots:   0 total
    Time:        1.379 s
    Ran all test suites.

This may be the long-term solution because Jest uses JSDom, and [JSDom is not supported by airtable.js](https://github.com/Airtable/airtable.js/tree/d8364a4ee49eb04f50e74b8c4463ca6b4a1a1fed#browser).

**Comment by Aias** [comment]
Hey @jugglinmike – `window.global` is not defined when I use Netlify's local cli. I'm surprised that it would be for you without additional setup, since these are supposed to be server-side functions.

**Comment by jugglinmike** [comment]
@Aias It's `global.window` that I'm wondering about, but not because it's defined in my environment. If some other code in the lambda environment (maybe via another dependency) defined that global variable, then it could interfere with [the logic that airtable.js 0.9.0 uses to identify which environment it is running in](https://github.com/Airtable/airtable.js/blob/v0.9.0/lib/abort-controller.js).

Looking deeper, I'm also curious about how airtable.js is being imported. The minimal test case uses Node.js's `require`, but that doesn't square with the error stack trace. Each frame references a file called `airtableGet.js`, but this library doesn't define such a file. The function names there **do** seem to align with the internals of this library, though. I first thought that Netlify's CLI was running a deployment-time bundling process, but the error stack seems to describe files on your development machine.

Do you know where `airtableGet.js` is coming from?

**Comment by Aias** [comment]
Ah sorry there's some confusion here, that's my fault.

On the window.global vs. global.window thing, I think I just miswrote the order before - in any case it doesn't matter, it's undefined either way.

`airtableGet` is the name of my lambda function, so it's what gets invoked when I send a request to `http://localhost:8888/.netlify/functions/airtableGet/`. Here's the stack trace which is just setting up a netlify dev environment with exactly that code from above, inside a file called airtableGet.js:

```
Error during invocation:  TypeError: AbortController is not a constructor
    at runAction (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:9585:22)
    at Base.runAction (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:4780:5)
    at inner (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:8111:27)
    at Query.eachPage (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:8134:5)
    at Query.eachPage (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:1665:16)
    at Object.exports.handler (/Users/tricknombley/Code/netlify-api/lambda/airtableGet.js:10666:6)
    at /Users/tricknombley/Code/netlify-api/node_modules/netlify-lambda/lib/serve.js:146:27
    at Layer.handle [as handle_request] (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/tricknombley/Code/netlify-api/node_modules/express/lib/router/route.js:131:14)
```

**Comment by Aias** [comment]
If you have a repository that works with airtable 0.9.0 and that minimal netlify test case, I'd be happy to clone it and see if it runs on my machine.

**Comment by jugglinmike** [comment]
Sure. Here's a repository using that same code:

https://github.com/bocoup/airtablejs-netlify-demo

When I change the values according to my account and Airtable Base schema, the lambda function development environment prints data from the Base as anticipated.

That may be a dead end, though, because the error stack trace above indicates that `airtableGet.js` is substantially different from the script we've been discussing. It references a number of functions that are not defined in that script. In addition, while the script is just 33 lines long, the frames in the stack trace reference line numbers in the thousands.

**Comment by Aias** [comment]
Thanks for all your help. Your example repo works. I was using the outdated netlify-lambda repository which does some kind of webpack compilation as part of its build step (I don't really understand the specifics). But when I switched everything from ES6 to CommonJS in my local repo, things started working again.

So I guess the moral is: drop dependency on `netlify-lambda`, use CommonJS module syntax?

**Comment by jugglinmike** [comment]
Sounds like a plan to me!

That build process appears to be modifying the environment, so it's effectively a new execution environment--just slightly different than the environments which Airtable explicitly supports. It doesn't seem feasible for this project's maintainers to ensure proper integration there (especially if it's considered outdated).

So while I'm receptive to evidence in favor of reverting the latest release, your particular problem doesn't seem to qualify as a regression. We still don't know much about @akarale's situation, though...

**Comment by studds** [comment]
I'm getting this error as well. I'm using airtable via node and webpack. There seems to be an issue with the node imports:

https://github.com/Airtable/airtable.js/blob/3d0ffc9f9deb249f61e8860399b2809fdab9e505/lib/fetch.js#L1 

and 

https://github.com/Airtable/airtable.js/blob/3d0ffc9f9deb249f61e8860399b2809fdab9e505/lib/abort-controller.js#L3

In each case, the require refers the the module, rather than the function / class respectively.

**Comment by itayplav** [comment]
`npm install webpack-node-externals --save-dev`

Create `webpack.functions.js` in your project root like so:

```
// webpack.functions.js
const nodeExternals = require('webpack-node-externals');
module.exports = {
    externals: [nodeExternals()],
  };
```
and modify your build command to be 

`netlify-lambda build lambda --config ./webpack.functions.js`

**Comment by mmeylan** [comment]
We're also experiencing the same error (`TypeError: AbortController is not a constructor`) when using `base.select().all()` and bundling our app with webpack.

**Comment by namgk** [comment]
any updates on this?

**Comment by Aias** [comment]
I believe this is fixed as of ^0.10.1. I've been using the latest version without issue.

**Comment by jaequery** [comment]
Hi, I'm getting the same issue on 0.11.1.

```
$ yarn test:mocks
$ TZ=UTC jest --config ./test/mocks/jest-mocks.json
 FAIL  test/mocks/all.load.ts
  ● Test suite failed to run
  ```
  
  ```
      > 6 | import * as Airtable from 'airtable';
```

```
      at Object.<anonymous> (../../node_modules/airtable/src/fetch.ts:5:76)
      at Object.<anonymous> (../../node_modules/airtable/src/base.ts:4:1)
      at Object.<anonymous> (../../node_modules/airtable/src/airtable.ts:1:1)
      at Object.<anonymous> (../../src/user/user.service.ts:6:1)
```

any help would be appreciated, thanks!

**Comment by namgk** [comment]
try the new node-fetch version 3, e.g. yarn add node-fetch@3.0.0-beta.9.

then remove the node_modules/airtable/node_modules

**Comment by calvin-tung** [comment]
Any update on this issue? I have been working on this

**Comment by calvin-tung** [comment]
**Workaround:**

Hosting my own node-fetch 2.6.7 and airtable, changing airtable's dependency to my own node-fetch and delete that few lines on node-fetch that caused error.

**Comment by Remzicik11** [comment]
**I am able to get around the problem by using node compact mode on the wrangler.**
The reason that airtable is not working is because that it uses the default ES6 modules but those modules are trimmed in wrangler so you need to import them separately or include them in the package.

_importing doesn't work so you can only include them internally which has some severe tradeoffs_

to include the modules you need to add this line to your wrangler.toml file
`node_compat = true`

**but doing so has the following tradeoffs** [`actual documentation`](https://github.com/ionic-team/rollup-plugin-node-polyfills/)
† the http and https modules are actually the same and don't differentiate based on protocol

‡ default export only, because it's console, seriously just use the global

§ vm does not have all corner cases and has less of them in a web worker

∆ not shimmed, just returns mock

**Comment by anridev24** [comment]
The issue has been open since **Aug 6, 2020**, please fix issue with that node-fetch package.

**Comment by bridger** [comment]
This should be fixed by our latest release, v0.11.6

**Comment by maxcan** [comment]
> This should be fixed by our latest release, v0.11.6

It is not.

**Comment by BridgerMaxwell-at** [comment]
Hey @maxcan, sorry this is still happening for you! Can you share more about the environment where this error is coming up? Is it in a browser, on a server, in a web worker, etc?

This error happens because we have a polyfill for environments that have `fetch` or not, or have a version of `fetch` which doesn't support AbortController. We need to know the exact environment to figure out when this polyfill should be activated or not.

**Comment by anridev24** [comment]
Hey @BridgerMaxwell-at, I'm getting error on AWS Lambda Functions, I'm using Serverless Framework 3.*, it worked fine locally with the "serverless-offline" plugin, right now I'm using "airtable@0.8.1" it has no error

**Comment by laurentperroteau** [comment]
It still not work in Node.js 18 in AWS Lambda with version `0.12.1` but I found a workaround overriding `node-fetch` dependencies to v3:

> Available since npm cli [v8.3.0](https://github.com/npm/cli/releases/tag/v8.3.0)

```json
    "airtable": "0.12.1"
  },
  "overrides": {
    "airtable": {
      "node-fetch": "^3.3.1"
    }
  }
```

**Comment by manuarora700** [comment]
Worked for me - Next.js 14, Airtable 0.12.2

```
const nextConfig = {
  experimental: {
    esmExternals: "loose",
  },
};
```

**Comment by clawrence121** [comment]
Working for me in Next 14: https://github.com/Airtable/airtable.js/issues/386#issuecomment-1994157555
